### PR TITLE
Add GitHub repo listing to aside-bar

### PR DESCRIPTION
**Pull request by BigBlueHat**
Using fetch and magic. ✨

### CODE REVIEW

**Comment by azaroth42** [comment]
Is there a preview for the change?

**Comment by iherman** [comment]
Indeed, a preview would be good. The list may become pretty long, with the approach we have of having a repo per document (if we have a separate document on HTTP issues, separate datasets from the core, have a note on YAML...)

**Comment by iherman** [comment]
Actually... I downloaded this version and ran jekyll locally. @azaroth42 here is a screen dump of how that would look like (see the lower right hand side). I am fine with it, so +1 from me.

screen shot 2018-08-03 at 09 31 04

**Comment by BigBlueHat** [comment]
Yeah, it could get long eventually, I suppose, but we could limit it and also hide the web site repo (and link it elsewhere).

I'm going to merge this, and hope that's OK. :wink:

**Pull request merged**
